BestParking/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
import os
admin.autodiscover()
def fromRelativePath(*relativeComponents):
    return os.path.join(os.path.dirname(__file__), *relativeComponents).replace("\\","/")

urlpatternstinymce = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

urlpatterns = patterns('',
    url(r'^$', 'home.views.home'),            
    url(r'^admin/', include(admin.site.urls)),
    url("^admin-media/(?P<path>.*)$",
    "django.views.static.serve",
    {"document_root": fromRelativePath("media", "admin-media")}),
    url(r'^findparking/$', 'FindParking.views.find_parking'),
    url(r'^tinymce/', include(urlpatternstinymce)),
    url(r'^useful/$', 'useful.views.loadInfo'),
    url(r'^findparking/ajaxCall/(?P<latlng>.*)$', 'FindParking.views.ajax_call'),
    url(r'^ajaxCall/(?P<latlng>.*)$', 'FindParking.views.ajax_call'),
    url(r'^useful/(?P<city>.*)$', 'useful.views.loadInfoForCity'),
             url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
)

home/models.py
from django.db import models

class HomePageNewsFeed(models.Model):
    info = models.TextField()
    title = models.CharField(max_length=45)
    def __unicode__(self):
        return str(self.title)

class Viewer(models.Model):
    email = models.CharField(max_length = 60)

class ParkingOwner(models.Model):
    email = models.CharField(max_length = 60)
    

home/forms.py
from django import forms

class LocationForm(forms.Form):
    """
    form containing fields for lat/lng coordinates,address and calendar
    """
    address = forms.CharField()
    lat = forms.FloatField()
    lng = forms.FloatField()
    hours = (
       (0, ("00")),
       (1, ("01")),
       (2, ("02")),
       (3, ("03")),
       (4, ("04")),
       (5, ("05")),
       (6, ("06")),
       (7, ("07")),
       (8, ("08")),
       (9, ("09")),
       (10, ("10")),
       (11, ("11")),
       (12, ("12")),
       (13, ("13")),
       (14, ("14")),
       (15, ("15")),
       (16, ("16")),
       (17, ("17")),
       (18, ("18")),
       (19, ("19")),
       (20, ("20")),
       (21, ("21")),
       (22, ("22")),
       (23, ("23")),
    )
    from_hour = forms.ChoiceField(choices=hours)
    to_hour = forms.ChoiceField(choices=hours)
    periods = (
       (00, ("00")),
       (15, ("15")),
       (30, ("30")),
       (45, ("45")),
    )
    from_period = forms.ChoiceField(choices=periods)
    to_period = forms.ChoiceField(choices=periods)
    from_date = forms.CharField();
    to_date = forms.CharField();

class SubscribeForm(forms.Form):
    email = forms.EmailField()
    is_parkingowner = forms.BooleanField(required=False)
    
class GetHomeParking(forms.Form):
    id = forms.CharField()

home/views.py
# -*- coding: utf-8 -*- 
from django.template import RequestContext
from django.contrib.sites.models import get_current_site
from django.shortcuts import render_to_response
from home.forms import LocationForm, SubscribeForm, GetHomeParking
from FindParking.models import ParkingMarker, ParkingFeatures, PaymentMethod
from home.models import HomePageNewsFeed
from django.contrib.sites.models import Site
from home.models import Viewer, ParkingOwner
from django.db import IntegrityError
import math

def home(request):  
    """
    function that take a request from the website
    and if request is GET then returns html with a form containing base values for 
    some fields: fromHour, toHour, fromPeriod, toPeriod
    if POST then takes the latitude and longitude coordinates of the address that the user has written
    as well as the address, then make SQL requests for near parkings and their features
    finally returns html with selected parkings 
    """
    if request.method == 'GET':
        return landing_page(request)
    else:
        if 'idParking' in request.POST:
            return fast_choice_parkings(request)  
        elif 'subsribeForm' in request.POST:
            return subscribe_user(request)
        elif 'addressForm' in request.POST:     
            return search_for_location(request)

def landing_page(request):
    subscribe_form = SubscribeForm()
    get_home_parking = GetHomeParking()
    address_form = LocationForm()
    parkings = ParkingMarker.objects.filter(onHomePage=True)#has to take parkings for homepage
    news_feed = HomePageNewsFeed.objects.all()
    context = {'getHomeParking':get_home_parking,'addressForm':address_form,'subscribeForm':subscribe_form,
               'parkings':parkings, 'newsFeed':news_feed, 'domain':get_current_site(request).domain}
    return render_to_response('home.html', context, context_instance=RequestContext(request))

def fast_choice_parkings(request):
    """
    renders the view when a parking from the quick bar (carousel) is selected
    on landing page (index.html)
    """
    subscribe_form = SubscribeForm()
    address_form = LocationForm()
    get_home_parking = GetHomeParking(request.POST)
    
    if get_home_parking.is_valid():
        #if form is valid redirect to map tempalte and show selected parking
        return show_picked_parking_on_map(request, subscribe_form, address_form, get_home_parking)
    else:
        #else redirect to landing page
        return render_landing_page(request, subscribe_form, address_form, get_home_parking)

def show_picked_parking_on_map(request, subscribe_form, address_form, get_home_parking):
    parking_id = get_home_parking.cleaned_data['id']
    parkings = ParkingMarker.objects.filter(onHomePage=True)
    features = [ParkingFeatures.objects.get(id=parking.features_id) for parking in parkings]
    paymentMethods = [PaymentMethod.objects.get(id=parking.paymentMethod_id) for parking in parkings]
    chosen_parking = ParkingMarker.objects.get(id=parking_id)
    lat = chosen_parking.lat
    lng = chosen_parking.lng
    address = chosen_parking.address
    context = {'addressForm':address_form,'subscribeForm':subscribe_form,'parkings':parkings,
                'chosenParking':chosen_parking,'features':features, 'paymentMethods':paymentMethods,
                'address':address, 'lat':lat, 'lng':lng, 'domain':Site.objects.get_current().domain}
    return render_to_response('findparking.html', context, context_instance=RequestContext(request))

def render_landing_page(request, subscribe_form, address_form, get_home_parking):
    subscribe_form = SubscribeForm()
    address_form = LocationForm()
    get_home_parking = GetHomeParking()
    parkings = ParkingMarker.objects.filter(onHomePage=True)#has to take parkings for homepage
    news_feed = HomePageNewsFeed.objects.all()
    context = {'getHomeParking':get_home_parking,'addressFrom':address_form,'subscribeForm':subscribe_form,
                'parkings':parkings,'newsFeed':news_feed, 'domain':Site.objects.get_current().domain}
    return render_to_response('home.html', context, context_instance=RequestContext(request))

def subscribe_user(request):
    """
    renders the view when user is subscribing by email
    on landing page (index.html)
    """
    subscribe_form = SubscribeForm(request.POST)
    address_form = LocationForm()
    get_home_parking = GetHomeParking()
    try:
        if subscribe_form.is_valid():
            return subscribe_and_return_message(request, subscribe_form, address_form, get_home_parking)
        else:
            return show_unvalid_form_message(request, subscribe_form, address_form, get_home_parking)
    except IntegrityError:
        return already_exist_message(request, subscribe_form, address_form, get_home_parking)

def subscribe_and_return_message(request, subscribe_form, address_form, get_home_parking):
    email = subscribe_form.cleaned_data['email']
    is_parkingowner = subscribe_form.cleaned_data['is_parkingowner']
    if is_parkingowner == True:
        to_add = ParkingOwner.objects.create(email = email)
        to_add.save()
                        #ParkingOwner.objects.
                        #ParkingOwner.save()
                        #send email
    else:
        to_add = Viewer.objects.create(email = email)
        to_add.save()
                        #send email
    parkings = ParkingMarker.objects.filter(onHomePage=True)#has to take parkings for homepage
    news_feed = HomePageNewsFeed.objects.all()
    context = {'message':"Благодарим Ви!",'openSubscribe':"openAndRefresh",'getHomeParking':get_home_parking,
                        'addressForm':address_form,'subscribeForm':subscribe_form,'parkings':parkings,'newsFeed':news_feed,
                         'domain':Site.objects.get_current().domain}
    return render_to_response('home.html', context, context_instance=RequestContext(request))

def show_unvalid_form_message(request, subscribe_form, address_form, get_home_parking):
    parkings = ParkingMarker.objects.filter(onHomePage=True)#has to take parkings for homepage
    news_feed = HomePageNewsFeed.objects.all()
    context = {'message':"Въведете валиден адрес!",'openSubscribe':"shouldOpen",'getHomeParking':get_home_parking,
                       'addressForm':address_form,'subscribeForm':subscribe_form,'parkings':parkings,'newsFeed':news_feed,
                        'domain':Site.objects.get_current().domain}
    return render_to_response('home.html', context, context_instance=RequestContext(request))

def already_exist_message(request, subscribe_form, address_form, get_home_parking):
    parkings = ParkingMarker.objects.filter(onHomePage=True)#has to take parkings for homepage
    news_feed = HomePageNewsFeed.objects.all()
    context = {'message':"Адресът вече е въведен!",'openSubscribe':"shouldOpen",'getHomeParking':get_home_parking,
                   'addressForm':address_form,'subscribeForm':subscribe_form,'parkings':parkings,'newsFeed':news_feed,
                    'domain':Site.objects.get_current().domain}
    return render_to_response('home.html', context, context_instance=RequestContext(request))

def search_for_location(request):
    """
    handles the request for a particular location from the seach bar
    """
    subscribe_form = SubscribeForm()   
    getHomeParking = GetHomeParking()
    address_form = LocationForm(request.POST)
    
    if address_form.is_valid():
        lat_address = address_form.cleaned_data['lat']
        lng_address = address_form.cleaned_data['lng']
        address = address_form.cleaned_data['address']
        parkings = [parking for parking in ParkingMarker.objects.all()
                             if distance([parking.lat, parking.lng], [lat_address, lng_address]) < 1]
        features = [ParkingFeatures.objects.get(id=parking.features_id) for parking in parkings]
        payment_methods = [PaymentMethod.objects.get(id=parking.paymentMethod_id) for parking in parkings]
        context = {'addressForm':address_form,'subscribeForm':subscribe_form, 'parkings':parkings, 'features':features,
                            'paymentMethods':payment_methods, 'address':address, 'lat':lat_address, 'lng':lng_address,
                             'domain':Site.objects.get_current().domain}
        return render_to_response('findparking.html', context , context_instance=RequestContext(request))
    else:
        parkings = ParkingMarker.objects.all()#has to take parkings for homepage
        news_feed = HomePageNewsFeed.objects.all()
        return render_to_response('home.html',
                                  {'getHomeParking':getHomeParking,'addressForm':address_form,
                                   'subscribeForm':subscribe_form, 'parkings':parkings,'newsFeed':news_feed,
                                    'domain':Site.objects.get_current().domain},
                                    context_instance=RequestContext(request))

def distance(origin, destination):
    """
    function that calculates and returns the distance between two points
    where each point has two values - latitude and longitude
    """
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371  # km

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) * math.sin(dlat / 2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon / 2) * math.sin(dlon / 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    d = radius * c

    return d

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Идеалното паркинг място за Вас</title>
		<link rel="shortcut icon" type="image/png" href="static/imgs/faviconParkingSector.png"/>
		<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"
		type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/index.css" >
		<link rel="stylesheet" type="text/css" href="/static/css/findparking.css" >
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
		<script src="http://code.jquery.com/jquery-1.7.1.js"></script>
		<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		<script src="/static/js/modernizr.js" type="text/javascript"></script>
		<script>
				jQuery(function($) {
				$("#id_from_date").datepicker({
					changeMonth : true,
					changeYear : true
				});
			});
			jQuery(function($) {
				$("#id_to_date").datepicker({
					changeMonth : true,
					changeYear : true
				});
			});
			
			</script>
		<script>
		
			// sets date
			function setDate() {
				var date = new Date();
				var minutes = date.getMinutes();

				if (0 <= minutes && minutes < 15) {
					document.getElementById('id_from_period').value = 45;
					document.getElementById('id_to_period').value = 45;
					document.getElementById('id_from_hour').value = date.getHours();
					var dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_from_date').value = dateString;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_to_hour').value = date.getHours();
					//	if (parseInt(document.getElementById('id_toHour').value) == 0)
					//	date.setDate(date.getDate() + 1);
					dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_to_date').value = dateString;
				} else if (15 <= minutes && minutes < 30) {
					document.getElementById('id_from_period').value = 0;
					document.getElementById('id_to_period').value = 0;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_from_hour').value = date.getHours();
					var dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_from_date').value = dateString;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_to_hour').value = date.getHours();
					//if (parseInt(document.getElementById('id_toHour').value) == 0)
					//	date.setDate(date.getDate() + 1);
					dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_to_date').value = dateString;
				} else if (30 <= minutes && minutes < 45) {
					document.getElementById('id_from_period').value = 15;
					document.getElementById('id_to_period').value = 15;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_from_hour').value = date.getHours();
					var dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_from_date').value = dateString;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_to_hour').value = date.getHours();
					//	if (parseInt(document.getElementById('id_toHour').value) == 0)
					//		date.setDate(date.getDate() + 1);
					dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_to_date').value = dateString;
				} else if (45 <= minutes && minutes < 60) {
					document.getElementById('id_from_period').value = 30;
					document.getElementById('id_to_period').value = 30;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_from_hour').value = date.getHours();
					var dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_from_date').value = dateString;
					date.setHours(date.getHours() + 1);
					document.getElementById('id_to_hour').value = date.getHours();
					//	if (parseInt(document.getElementById('id_toHour').value) == 0)
					//		date.setDate(date.getDate() + 1);
					dateString = date.getMonth() + 1 + "/" + date.getDate() + "/" + date.getFullYear();
					document.getElementById('id_to_date').value = dateString;
				}
			}

			// colors the tab to show which page the user is on
			function colorNavElement() {
				if (document.getElementById('pageId').className == "home") {
					document.getElementById('homeNav').style.backgroundColor = "rgb(27,162,217)";
					document.getElementById('homeNav').style.borderRadius = "7px";
				}
				if (document.getElementById('pageId').className == "findParking") {
					document.getElementById('findNav').style.backgroundColor = "rgb(27,162,217)";
					document.getElementById('findNav').style.borderRadius = "7px";
				}
				if (document.getElementById('pageId').className == "useful") {
					document.getElementById('usefulNav').style.backgroundColor = "rgb(27,162,217)";
					document.getElementById('usefulNav').style.borderRadius = "7px";
				}
			}

			// makes some elements read-only
			function readOnly() {
				document.getElementById('id_from_date').readOnly = true;
				document.getElementById('id_to_date').readOnly = true;
				document.getElementById('id_address').placeholder = "Ще паркирам в близост до ..";
			}

			function parseParkings(arr) {
				{% for parking in parkings %}
				var loadParking = new Object();
				loadParking.id = "{{ parking.id }}";
				loadParking.name = "{{parking.name}}";
				loadParking.address = "{{parking.address}}";
				loadParking.lat = parseFloat("{{parking.lat}}");
				loadParking.lng = parseFloat("{{parking.lng}}");
				loadParking.distance = distance("{{lat}}", "{{lng}}", "{{parking.get_lat}}", "{{parking.get_lng}}");
				loadParking.image = "{{ parking.image }}";
				loadParking.capacity = "{{ parking.capacity }}";
				loadParking.workFrom = "{{ parking.workFrom }}";
				loadParking.workTo = "{{ parking.workTo }}";
				loadParking.pricePerHour = "{{ parking.pricePerHour }}";
				loadParking.paymentmethod = "{{ parking.paymentMethod }}";
				loadParking.features = parseInt("{{ parking.features }}");
				arr.push(loadParking);
				{% endfor %}
			}

			// calculates the distance between two points
			function distance(latAddress, lngAddress, lat, lng) {
				Math.radians = function(degrees) {
					return degrees * Math.PI / 180;
				};
				var R = 6371;
				// Radius of the earth in km
				var dLat = Math.radians(lat - latAddress);
				// Javascript functions in radians
				var dLon = Math.radians(lng - lngAddress);
				var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(Math.radians(latAddress)) * Math.cos(Math.radians(lat)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
				var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
				var d = R * c;

				return d;
			}

			// if departure time is at least 1 hour after arrival time
			function checkForProperTimeDuration() {
				var fromHour = parseInt(document.getElementById('id_from_hour').value);
				var toHour = parseInt(document.getElementById('id_to_hour').value);
				var fromPeriod = parseInt(document.getElementById('id_from_period').value);
				var toPeriod = parseInt(document.getElementById('id_to_period').value);

				var dateFrom = document.getElementById('id_from_date').value.split('/');
				var monthFrom = parseInt(dateFrom[0]) - 1;
				var dayFrom = parseInt(dateFrom[1]);
				var yearFrom = parseInt(dateFrom[2]);

				var dateTo = document.getElementById('id_to_date').value.split('/');
				var monthTo = parseInt(dateTo[0]) - 1;
				var dayTo = parseInt(dateTo[1]);
				var yearTo = parseInt(dateTo[2]);

				var starttime = (new Date(yearFrom, monthFrom, dayFrom, fromHour, fromPeriod, 0)).getTime();
				var endtime = (new Date(yearTo, monthTo, dayTo, toHour, toPeriod, 0)).getTime();

				if (endtime >= starttime && ((endtime / 3600000) - (starttime / 3600000)) >= 1)
					return true;
				return false;
			}
		</script>
		<script>
			$(function() {
				$("#OpenPanel").click(function() {
					var el = document.getElementById('content-box');
					if (el.style.width != "472px") {
						$("#content-box").animate({
							'width' : 472
						}, 350);
						setTimeout(function() {
							document.getElementById('boxContent').style.visibility = "visible";
							document.getElementById('subscribeButton').value = 'subscribe';
						}, 350);
					}
				});
			});

			$(function() {
				$("html").click(function() {
					var el = document.getElementById('content-box');
					if (el.style.width == "472px") {
						if (!IsMouseOver('content-box')) {
							$("#content-box").animate({
								'width' : 140
							}, 350);
							document.getElementById('boxContent').style.visibility = "hidden";
						}
					}
				});
			});

			$(function() {
				$("#OpenPanel").click(function() {
					var el = document.getElementById('content-box');
					if (el.style.width == "472px") {

						$("#content-box").animate({
							'width' : 140
						}, 350);
						document.getElementById('boxContent').style.visibility = "hidden";

					}
				});
			});

			function IsMouseOver(oi) {
				return $("#" + oi + ":hover").length > 0;
			}
			
			function setFocus() {
			    document.getElementById("id_address").focus();
			}

		</script>
		<script>
			function checkForSubscribe() {
				if ("{{ openSubscribe }}" == "shouldOpen") {
					var el = document.getElementById('content-box');
					if (el.style.width != "472px") {
						$("#content-box").animate({
							'width' : 472
						}, 350);
						setTimeout(function() {
							document.getElementById('boxContent').style.visibility = "visible";
							document.getElementById('subscribeButton').value = 'subscribe';
						}, 350);
					}
				} else if ("{{ openSubscribe }}" == "openAndRefresh") {
					var el = document.getElementById('content-box');
					if (el.style.width != "472px") {
						$("#content-box").animate({
							'width' : 472
						}, 350);
						setTimeout(function() {
							document.getElementById('id_email').value = "";
							document.getElementById('boxContent').style.visibility = "visible";
							document.getElementById('subscribeButton').value = 'subscribe';
						}, 350);
					}
				}
			}
		</script>
		{% block extrahead %}
		{% endblock %}
	</head>
	<body>
		<div id="wrapper">
			<header>
				<div>
					<span id="logoImage">
						<input type="image" src="/static/imgs/Logo.png"/>
					</span>
					<span>
						<input type="image" src="/static/imgs/beta_stamp.png" />
					</span>
					<!-- logo line image to be implemented data-href="https://www.facebook.com/IvanKavaldzhievPhotography"-->
					<!-- register/sign in to be implemented -->
				</div>
			</header>
			<nav>
				<div id="navigationMenu">
					<div id="navMenu">
						<!-- href="http://{{domain}}" -->
						<a class="nav" id="homeNav" href="/">Начало</a>
						<a class="nav" id="findNav" href="/findparking/">Намери паркинг</a>
						<!--<a id="usefulNav" href="http://127.0.0.1:8000/useful/">Полезно</a>-->
						<a id='twitterRef' href="http://www.youtube.com"></a>
						<a id="facebookRef" href="http://www.youtube.com"></a>
					</div>
				</div>
			</nav>
			<div id="content-box">
				<div id="OpenPanel">
					<div>
						Абонирай се!
					</div>
				</div>
				<div id="boxContent">
					<div id="boxLine">
						Ако желаеш да си информиран преди останалите!
					</div>
					<div id="emailLine">
						Въведете вашия е-мейл.
					</div>

					<form action="" method="post" id="subscribe">
						{% csrf_token %}

						{{ subscribeForm.email }}
						{{ subscribeForm.is_parkingowner }}
						<div id="checkLine">
							<label for="id_is_parkingowner">Кликнете, ако управлявате паркинг и желаете допълнително информация.</label>
						</div>
						<input type="submit" id="subscribeButton" name="subsribeForm" value="Намери"/>
						<p style="float:left;margin:10px 0 0 10px; color: rgb(27,162,217);">
							{{message}}
						</p>
					</form>
				</div>
			</div>
			{% block content %}
			{% endblock %}
			<footer>
				<div style="float:right;margin:10px 0 0 250px;">
					<div style="float:left;">
						<iframe src="//www.facebook.com/plugins/like.php?href=https://www.facebook.com/ParkingSector&amp;width&amp;layout=box_count&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=65" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:65px;width:100px;" allowTransparency="true"></iframe>
					</div>
					<div style="float:left;margin-right:40px;">
						<iframe scrolling="no" frameborder="0" allowtransparency="true" src="https://platform.twitter.com/widgets/tweet_button.1352365724.html#_=1354037601139&amp;count=vertical&amp;id=twitter-widget-3&amp;lang=en&amp;original_referer=https%3A%2F%2Fdev.twitter.com%2Fdocs%2Ftweet-button%2Ffaq%23custom-shortener-count&amp;size=m&amp;text=Намерих елегантното решение на проблема с паркирането ... www.parkingsector.bg&amp;url=https://twitter.com/ParkingSector&amp;" class="twitter-share-button twitter-count-vertical" style="width: 55px; height: 62px;" title="Twitter Tweet Button" data-twttr-rendered="true"></iframe>
					</div>
				</div>
				<div id="contacts"></div>
				<div id="footer">

				</div>
				<div style="float:left;text-align:center;width:960px;margin:10px 0 10px 0;">
					Copyright &copy; 2014
				</div>

			</footer>
	</body>
</html>